# Generated by Django 3.2.25 on 2024-07-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0011_merge_20200916_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(choices=[('US', 'United States of America'), ('CH', 'China')], max_length=25, verbose_name='The location of place'),
        ),
    ]
